exclude: |
    (?x)(
        setup.py |
        ^docs/ |
        alembic/
    )

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-docstring-first
          - id: debug-statements

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.15.0
      hooks:
          - id: mypy
            args:
                - --explicit-package-bases
                - --ignore-missing-imports
                - --check-untyped-defs
            exclude: ^tests/
            additional_dependencies:
              - types-requests==2.32.*
              - types-PyYAML==6.0.*
              - types-pyOpenSSL==24.1.*

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.5
      hooks:
          - id: ruff
            args:
              - --fix
              - --exit-non-zero-on-fix
          - id: ruff-format
    - repo: https://github.com/hadolint/hadolint
      rev: v2.12.0
      hooks:
          - id: hadolint-docker
            args: [
              "--ignore", "DL3008",
              "--ignore", "DL3013",
              "--ignore", "DL3018",
              "--failure-threshold", "warning",
            ]
